[PROTOCOLS]

Protocols SPA = [
	{"tag": "section", "text": "3D", "children": [
		{"tag": "protocol_group", "text": "Reconstruct", "openItem": "False", "children": [
          {"tag": "protocol", "value": "ProtMICA", "text": "default"}
    ]},
    {"tag": "protocol_group", "text": "Preprocess", "openItem": "False", "children": [
	]}]